/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/ui/BaseCard.vue')['default']
    BaseFileUpload: typeof import('./src/components/form/BaseFileUpload.vue')['default']
    BaseInput: typeof import('./src/components/form/BaseInput.vue')['default']
    BaseSelect: typeof import('./src/components/form/BaseSelect.vue')['default']
    BaseTextarea: typeof import('./src/components/form/BaseTextarea.vue')['default']
    ButtonShowcase: typeof import('./src/components/demo/ButtonShowcase.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    LoadingBar: typeof import('./src/components/ui/LoadingBar.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OtpFlow: typeof import('./src/components/ui/OtpFlow.vue')['default']
    PDFViewer: typeof import('./src/components/ui/PDFViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentTransferList: typeof import('./src/components/admin/StudentTransferList.vue')['default']
    TujuanCard: typeof import('./src/components/TujuanCard.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFileUpload: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
